SELECT * FROM ID_G_INPUT_DATE ORDER BY G_INPUT_DATE    DESC      ;


SELECT
    IG.G_PIC                                "PIC"
    ,IG.G_ITEM_CODE                        "ITEM_CODE"
    ,IG.G_ITEM_NAME                        "ITEM_NAME"
    ,IGI.G_STOCK_IN_CNT                         "STOCK_IN_CNT"
    ,TO_CHAR(IGI.G_INPUT_DATE, 'YYYY-MM-DD HH24:MI' )   "INPUT_DATE"
    ,TO_CHAR(IG.G_BUILD_DAY,'YYYY-MM')                         "BUILD_DAY"
    ,IG.G_DISCONTINUED                      "DISCONTINUED"
    ,IG.ENERGY_GRADE_CODE                   "ENERGY_GRADE_CODE"
    ,IG.COLOR_CODE                          "COLOR_CODE"
    ,IG.BRAND_CODE                          "BRAND_CODE"
    ,IG.G_POWER_CONSUM                      "POWER_CONSUM"
    ,IG.CATEGORY_CODE                       "CATEGORY_CODE"
    ,IC.CATEGORY_NAME                       "CATEGORY_NAME"
    ,IG.G_SUB_CATEGORY_CODE                 "SUB_CATEGORY_CODE"
    ,IGSC.G_SUB_CATEGORY_NAME               "SUB_CATEGORY_NAME"
    ,IG.G_SUB_SUB_CATEGORY_CODE             "SUB_SUB_CATEGORY_CODE"
    ,IGSSC.G_SUB_SUB_CATEGORY_NAME          "SUB_SUB_CATEGORY_NAME"
    ,nvl(GIPS.G_INSTOCK,0)-nvl(GOPS.G_OUTSTOCK,0) "STOCK"
FROM

  ID_G_ITEMS IG, ID_G_INPUT_DATE IGI

  ,ID_CATEGORIES IC
  ,ID_G_SUB_CATEGORY IGSC
  ,ID_G_SUB_SUB_CATEGORY IGSSC
  ,(select  IG.G_ITEM_CODE ,nvl(SUM(IGI.G_STOCK_IN_CNT),0) "G_INSTOCK" from
        ID_G_ITEMS IG inner join ID_G_INPUT_DATE IGI on IG.G_ITEM_CODE=IGI.G_ITEM_CODE group by IG.G_ITEM_CODE)  GIPS
  ,(select  IG.G_ITEM_CODE ,nvl(SUM(IGO.G_STOCK_OUT_CNT),0) "G_OUTSTOCK" from
        ID_G_ITEMS IG inner join ID_G_OUTPUT_DATE IGO on IG.G_ITEM_CODE=IGO.G_ITEM_CODE group by IG.G_ITEM_CODE) GOPS

WHERE

IG.G_ITEM_CODE(+) = IGI.G_ITEM_CODE

AND

IC.CATEGORY_CODE(+) = IG.CATEGORY_CODE

AND

IGSC.G_SUB_CATEGORY_CODE(+) = IG.G_SUB_CATEGORY_CODE

AND

IGSSC.G_SUB_SUB_CATEGORY_CODE(+) = IG.G_SUB_SUB_CATEGORY_CODE


AND

GIPS.G_ITEM_CODE=IG.G_ITEM_CODE


AND
GOPS.G_ITEM_CODE=IG.G_ITEM_CODE







AND

upper(IGI.G_ITEM_CODE) like upper('%ATQE430-JWK%')

--  IGI.G_ITEM_CODE = 'AF16M6476LZR'

ORDER BY  G_INPUT_DATE DESC;


--

SELECT * FROM ID_G_OUTPUT_DATE ORDER BY G_OUTPUT_DATE    DESC      ;

SELECT
    IG.G_PIC
    ,IGI.G_ITEM_CODE
    ,IGI.G_STOCK_OUT_CNT
    ,IGI.G_OUTPUT_DATE
    ,IG.G_DISCONTINUED
    ,IG.CATEGORY_CODE
    ,IC.CATEGORY_NAME
    ,IG.G_SUB_CATEGORY_CODE
    ,IGSC.G_SUB_CATEGORY_NAME
    ,IG.G_SUB_SUB_CATEGORY_CODE
    ,IGSSC.G_SUB_SUB_CATEGORY_NAME

FROM

  ID_G_ITEMS IG, ID_G_OUTPUT_DATE IGI

  ,ID_CATEGORIES IC
  ,ID_G_SUB_CATEGORY IGSC
  ,ID_G_SUB_SUB_CATEGORY IGSSC

WHERE

IG.G_ITEM_CODE(+) = IGI.G_ITEM_CODE

AND

IC.CATEGORY_CODE(+) = IG.CATEGORY_CODE

AND

IGSC.G_SUB_CATEGORY_CODE(+) = IG.G_SUB_CATEGORY_CODE

AND

IGSSC.G_SUB_SUB_CATEGORY_CODE(+) = IG.G_SUB_SUB_CATEGORY_CODE


AND 1=1

ORDER BY  G_OUTPUT_DATE DESC;






 SELECT * FROM ID_G_INPUT_DATE ORDER BY G_INPUT_DATE    DESC      ;




DELETE FROM  ID_G_INPUT_DATE WHERE  G_INPUT_DATE_NO = 172

COMMIT


 sELECT * FROM ID_G_outPUT_DATE ORDER BY G_outPUT_DATE    DESC      ;


    DELETE FROM  ID_G_outPUT_DATE WHERE  G_outPUT_DATE_NO = 101